### PR TITLE
XmlBuilder for XmLayout

### PR DESCRIPTION
**Pull request by 304NotModified**
@snakefoot  your opionion please :)

### CODE REVIEW

**Comment by snakefoot** [comment]
Would prefer a mutable struct, instead of a class. But can see the idea especially with RawValues coming.

**Comment by 304NotModified** [comment]
why is that? We where passing the stringbuilder refence, and now the XMLbuilder reference.

**Comment by snakefoot** [comment]
Well I don't like allocations. Cannot see that the StringBuilder is being allocated :)

And if you look closely, then `ContentWritten` is not a valid replacement, since it the logic is whether something has been written within a scope. The correct logic would be to create a XMLbuilder for each scope. Thus it becomes even more critical that it is a mutable struct.

Could make the XmlBuilder-struct inherit from IDisposable-interface so you could apply `using`-statement around a scope. Thus automatic handling of scope-completion.

**Comment by 304NotModified** [comment]
> since it the logic is whether something has been written within a scope.

Indeed, this is incorrect now.

fair enough, close for now

**Pull request closed without merging**
